FROM elasticsearch:2.3.3
MAINTAINER Ernest Mueller <ernestmueller@theagileadmin.com>

RUN /usr/share/elasticsearch/bin/plugin install --batch cloud-aws
RUN /usr/share/elasticsearch/bin/plugin install --batch mapper-size
