---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[my_cookbook::default]
